blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss ideas
    url: https://github.com/zachzama/siggy/discussions
    about: Ask questions, share ideas, and engage with the community.
